VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "casefasade"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True

 Public name As String
 Public size As Integer
 Public qty As Integer
 Public dopinfo As String
 Public qty_string As String
 Public isSmall As Boolean
 Public isBig As Boolean
 Public isNisha As Boolean
 Public isDveri As Boolean
 Public isVitr As Boolean
 Public isShuflyada As Boolean
 Public napravl As String
 Public frawstring As String
 Public fOption As String
 Public fCustomerFur As Boolean
 Sub init()
 fCustomerFur = False
 name = ""
 size = 0
 qty = 0
 dopinfo = ""
 qty_string = ""
 isSmall = False
 isBig = False
 isNisha = False
 isDveri = False
 isShuflyada = False
 isVitr = False
 napravl = ""
 frawstring = ""
 fOption = ""
 End Sub
 
 



