VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "caseFurniture"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

 Public fName As String
 Public fOption As String
 Public fLength As String
 Public fType As String
 Public caseElement As String
 Public qty As Integer
 Sub init()
 fName = ""
 fOption = Empty
 qty = 0
 caseElement = ""
 fLength = ""
 fType = ""
 End Sub
 
 




